/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cpsinjhffmjwukvmlcmz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwc2luamhmZm1qd3Vrdm1sY216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MTkyMDIsImV4cCI6MjA5MDE5NTIwMn0.x9yrlcO-Ji0bWzwgdAr_zZTcLSgDCWy-4mZzJbko4BY"